# Generated by Django 4.1.7 on 2023-02-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB',
            new_name='Database',
        ),
    ]
